import { QUIZ_LEVEL, QUIZ_TYPE } from "./quizz";

export type BookData = {
  actived: boolean;
  bookGroup: string;
  bookGroupDescription: null;
  bookTypeId: null;
  bookTypeName: null;
  canDownload: boolean;
  copyRight: string;
  createAt: string;
  description: string;
  gkClassId: null | string;
  id: number;
  imageUrl: string;
  lastUpdated: string;
  limitActivePage: number;
  limitPage: number;
  manufactureYear: string;
  name: string;
  slug: string;
  subjectId: null | string;
  subjectName: null | string;
  totalPage: number;

  // bookGroupId: string;
  // bookId: number;
  // bookTypeId: string;
  // classId: string;
  // completeDate: string | null;
  // copyRight: null | string;
  // createdAt: string;
  // editionYear: string;
  // id: string;
  // imageUrl: string;
  // isActived: boolean;
  // isDeleted: boolean;
  // lastUpdated: null | string;
  // levelId: null | number;
  // manufactureYear: string;
  // name: string;
  // slug: string;
  // subjectId: string;
  // total: null | number;
  // totalPage: null | number;
};

export type RecentlyBookData = {
  id: number;
  name: string;
  description: string;
  slug: string;
  imageUrl: string;
  copyRight: string;
  lastUpdated: null;
  createAt: null;
  manufactureYear: string;
  totalPage: number;
  actived: null;
  canDownload: null;
  bookGroupDescription: null;
  gkClassId: null;
  bookTypeId: null;
  bookTypeName: null;
  subjectId: null;
  subjectName: null;
  limitPage: null;
  limitActivePage: null;
  bookGroup: {
    id: number;
  };
  underscoreName: null;
  lastSeen: string;
};
export type BookDetailData = {
  bookFileVersionItemIds: null | string;
  bookId: null | number;
  name: string;
  id: null | number;
  items: BookPage[];
};

export type BookCommonData = {
  id: 2010;
  name: string;
  slug: string;
  description: string | null;
  imageUrl: string;
  tags: null;
  manufactureYear: string;
  editionYear: string;
  copyRight: string;
  bookAuthorList: string[];
  bookEditorList: string[];
  completeDate: string;
  lastUpdated: string;
  isDeleted: null;
  gkClass: { id: number };
  bookGroup: { id: number };
  createAt: string;
  updateAt: string;
  totalPage: number;
  fileName: string;
  bookPdfLowQualityFileName: null;
  isSample: null;
  actived: boolean;
  canDownload: boolean;
  limitPage: number;
  trainingName: "";
  limitActivePage: number;
  limitPracticeY: number;
  limitPracticeX: number;
  bookGroupDescription: null;
  lastQuestionId: number;
  bookmarkPage: number;
};
export type BookClassId = {
  id: number;
  name: string;
  isDeleted: boolean;
  books: null;
  children: null;
  // classId: number;
  // classNo: number;
  // createdAt: string;
  // description: null | string;
  // id: string;
  // imageUrl: null | string;
  // isDeleted: boolean;
  // name: string;
  // slug: null | string;
  // updatedAt: string;
};
export type BookIndexs = {
  createAt: null;
  id: number;
  isDeleted: null;
  children: BookIndexs[];
  name: string;
  orderNo: number;
  pageNo: number;
  parentId: null | string;
  slug: string;
  title: string;
  updateAt: null;
};

export type BookPage = {
  bookFileVersionId: null | string;
  bucket: null;
  contentType: null | string;
  fileKey: string;
  fileUrl: string;
  id: null | string;
  page: null | number;
};
export type BookLearningMaterialsData = {
  bookId: string;
  createdAt: string;
  id: string;
  indexId: string;
  isDelete: boolean;
  linkUrl: string;
  page: number;
  pageId: null;
  posterLink: string;
  titleLink: string;
  type: string;
  updatedAt: string;
};

export type BookSubjectsData = {
  // createdAt: string;
  // deletedAt: null | string;
  // description: null | string;
  // id: string;
  // imageUrl: null | string;
  // isDeleted: boolean;
  // name: string;
  // slug: null | string;
  // subjectId: number;
  // updatedAt: string;

  books: null;
  createAt: string;
  description: string;
  id: number;
  imageUrl: string;
  isDeleted: boolean;
  name: string;
  orderNo: number;
  slideImageUrl: string;
  slideTitle: string;
  updateAt: string;
};
export type BookGroupsData = {
  id: number;
  name: string;
  description: string;
  orderNo: number;
  isShowPlatform: boolean;
  isDeleted: boolean;
  books: null;
  // bookGroupId: number;
  // createdAt: string;
  // id: string;
  // isDeleted: null | string;
  // name: string;
  // orderNo: number;
};
export type BookTypesData = {
  bookTypeId: number;
  createdAt: string;
  description: null | string;
  id: string;
  imageUrl: null | string;
  isDeleted: boolean;
  name: string;
  slideImageUrl: null | string;
  slideTitle: null | string;
  updatedAt: string;
};
export type BookQuestionAnswerData = {
  code: string;
  content: string;
  correct: string;
  createdAt: string;
  id: string;
  imageUrl: null | string;
  isDeleted: boolean;
  isTrue: boolean;
  questionId: string;
  status: "correct" | "wrong" | "none" | "selected";
  type: null;
  updatedAt: string;
};
export type BookQuestionData = {
  answerDetail: null | string;
  audioUrl: null | string;
  bookId: string;
  content: string;
  createBy: null | string;
  createdAt: string;
  explain: null | string;
  id: string;
  imageUrl: null | string;
  isDeleted: boolean;
  level: QUIZ_LEVEL;
  pageNo: null | number;
  quizId: string;
  suggestion: null | string;
  text: null | string;
  title: null | string;
  totalTime: number;
  type: QUIZ_TYPE;
  updatedAt: "2024-10-15T08:30:13.789072+00:00";
};
export type BookQuestionsAnswersConfig = {
  answerId: string;
  createdAt: string;
  data: null | { content?: string };
  draggable: boolean;
  height: number | null;
  id: string;
  parentId: null;
  position: { x: number; y: number; originalX: number; originalY: number };
  questionId: string;
  type: null;
  updateAt: string;
  width: null | number;
};
